name: Bun Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Bun
      uses: oven-sh/setup-bun@v1
      
    - run: bun i
    - run: bun run docs:build

    - run: |
        git config user.name loong.woo
        git config user.email longwunet@outlook.com
        git add .
        git commit -m "deploy"
        git push --force-with-lease
