name: Bun Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Bun
      uses: oven-sh/setup-bun@v1
      
    - run: bun i
    - run: bun run build:docs
